---
# Add entries to this file to generate them automatically upon running
# rake record_loader:all or rake record_loader:<%= underscore %>
# If you want entries which are only created in development mode then simply
# create a file in this directory ending in '.dev.yml'
# You can add as many additional .yml files to this directory as you wish.
# Note: This data was dumped from production on 2020-07-02
Reception fridge:
  barcode: '010430'
P200 Pipette:
  barcode: 'WG0206799-DNA'
Volume checker_old:
  barcode: '009867'
Beckman NX:
  barcode: '009851'
Beckman FX:
  barcode: '010468'
DTX 1:
  barcode: '010464'
DTX 2:
  barcode: '010456'
Tecan 1:
  barcode: '014296'
Tecan 2:
  barcode: '014297'
Tecan 3:
  barcode: '014218'
Delivery freezer:
  barcode: '009886'
Left SLF:
  barcode: 'WG0112207-DNA'
Tecan 4:
  barcode: '014219'
Destroying instrument:
  barcode: '6720000011694'
Biorobot:
  barcode: '4880001006869'
Tecan 5:
  barcode: '015434'
Tecan 6:
  barcode: '015435'
Bravo:
  barcode: '4880000059873'
Mosquito 1:
  barcode: '23860-1'
Mosquito 2:
  barcode: '23861-1'
Volume Checker_new:
  barcode: '036678'
Hamilton Star 6:
  barcode: '4880000067878'
